### ISSUE TITLE
Quick question!

### ISSUE THREAD

**Issue by Kladdkaka** [ivolimasilva/public-instagram#11]
Hello!

Thanks for this library, it seems to fit my needs perfectly.

I only got one question though, what is the reasoning for using Puppeteer for stuff like this? https://github.com/ivolimasilva/public-instagram/blob/master/lib/users/index.js#L102

Just seems a bit expensive to run a whole browser to get a id, but just wondering if there is any reason I do not know behind it? :D 

Cheers
/ Erik

**Comment by Kladdkaka** [comment]
btw don't take this as criticism or anything haha, just was curios :D

**Comment by ivolimasilva** [comment]
hey there, thanks for your comment :smile: 

I looked at what some other scrappers were doing in regards to `query_id` and they all had it hard coded.
I just didn't trust Instagram enough to let it hard coded and wait if it would break at any given day.
So I used [Puppeteer](https://github.com/GoogleChrome/puppeteer) for that.

However, after using it in real conditions, Puppeteer is in fact to heavy for this use and I plan to rewrite (at least) that part for the lib to be more usable.

Thanks for the feedback & discussion, it's always welcome :+1:

**Comment by Kladdkaka** [comment]
Hey!

Thank you for the answer, and that makes sense :) Instagram seems to be really unpredictable with their api, hehe.

I am doing a rewrite myself, as this seemed like a nice base to use, will upload it to github when I have made some progress, and then you can use the parts you want :D 

Thank you once again! And hopefully I will make some stuff you could use :D

**Comment by ivolimasilva** [comment]
I'm the one who thanks you. Every feedback is welcome!

If you find a way to fetch the `query_id` that doesn't bottlenecks this package, I will use it immediately 😃

**Comment by Kladdkaka** [comment]
:)

Well, about query_id, I tried to do some fun stuff with regex, but then realized that it would not be feasible, as the id's were located completely different (some of them was hardcoded into the function call, some of them was in own variables)

But I found this https://github.com/timgrossmann/InstaPy-Research, an idea could be to ask them if it would be possible to put their query_ids in a json file that could be fetched from github.

But I also asked myself if it was really a problem, I mean, I have a slight feeling that Instagram won't change the ids, unless they change the response json format too, it might be a good idea that it just doesn't work then, to prevent suprises. What would you think? :)
