### ISSUE TITLE
user post limit

### ISSUE THREAD

**Issue by paOol** [ivolimasilva/public-instagram#2]
there should be a `limit` parameter for users.posts();

even the 'instagram' example takes like 30 seconds and loads the users' entire history.

**Comment by ivolimasilva** [comment]
This is fixed by #4 :+1:

**Comment by paOol** [comment]
did you run `npm publish` again?
I'm not seeing the version update on npm.

**Comment by ivolimasilva** [comment]
Was still running :laughing: it's up now!
